code4moldova/voluntar-backend

- backend/endpoints/beneficiary.py
> added filters for beneficiary

- backend/app.py
- backend/endpoints/__init__.py
- backend/endpoints/beneficiary.py
- backend/endpoints/operator.py
> Assign request to a fixer

- backend/config.py
- backend/endpoints/geo.py
- backend/endpoints/volunteer.py
- backend/models/volunteer_model.py
> Calc distance in km

- Dockerfile
- backend/app.py
- backend/endpoints/volunteer.py
- backend/models/volunteer_model.py
new endpoint /api/volunteer/csv/ to build csv
> Export volunteers as csv

- .github/workflows/pythonapp.yml
- Pipfile
- Pipfile.lock
- README.md
- backend/app.py
- backend/config.py
- backend/endpoints/auth.py
- backend/endpoints/export.py
- backend/endpoints/operator.py
- backend/endpoints/welcome.py
- backend/models/volunteer_model.py
- backend/seeds.py
- backend/server.py
- backend/services/table_list.py
- backend/tests/__init__.py
- backend/tests/conftest.py
- backend/tests/endpoints/test_auth.py
- backend/tests/endpoints/test_export.py
- backend/tests/endpoints/test_welcome.py
- backend/tests/factories.py
- backend/tests/services/test_table_list.py
- backend/tests/unit/test_operator.py
- pytest.ini
A full list of fields should be included, I selected few for POC.
closes #56
> Export beneficiaries as csv

- .github/workflows/pythonapp.yml
- Pipfile
- Pipfile.lock
- README.md
- backend/app.py
- backend/config.py
- backend/endpoints/auth.py
- backend/endpoints/operator.py
- backend/endpoints/welcome.py
- backend/models/volunteer_model.py
- backend/seeds.py
- backend/server.py
- backend/tests/__init__.py
- backend/tests/conftest.py
- backend/tests/endpoints/test_auth.py
- backend/tests/endpoints/test_welcome.py
- backend/tests/factories.py
- backend/tests/unit/test_operator.py
- pytest.ini
> Testing and user seeds

- Pipfile
- Pipfile.lock
- backend/app.py
- backend/endpoints/__init__.py
- backend/endpoints/beneficiary.py
- backend/endpoints/telegrambot.py
- backend/endpoints/volunteer.py
- backend/utils/volunteer_utils.py
> Fast endpoints: chatbot

- .github/workflows/pythonapp.yml
- Dockerfile
- Pipfile
- Pipfile.lock
- backend/services/table_list.py
Closes #77 
Tested on local machine using restapi client
> Correct the export columns

- backend/endpoints/beneficiary.py
- backend/endpoints/beneficiary_requests.py
- backend/endpoints/volunteer.py
- backend/models/__init__.py
- backend/models/beneficiary_model.py
- backend/models/cluster_model.py
- backend/models/enums.py
- backend/models/notifcation_user_model.py
- backend/models/notification_model.py
- backend/models/request_model.py
- backend/models/user_model.py
- backend/models/volunteer_model.py
- backend/seeds.py
Closed #91 #92 #93 #90 #89 #88 #84
> Create Request model

- .gitignore
- CONTRIBUTING.md
- README.md
It updates the website link of code4md. Not major
> doc update and gitignore addition for vscode

- backend/app.py
- backend/endpoints/beneficiary.py
> readd tag endpoint and add status key for beneficiary filter

- backend/endpoints/user_request.py
- backend/services/request_service.py
> added id and status filter for requests, fixed the request creation

- backend/app.py
- backend/endpoints/__init__.py
- backend/endpoints/notification.py
- backend/models/__init__.py
- backend/models/notifcation_user_model.py
- backend/models/notification_model.py
- backend/seeds.py
- backend/static/swagger.yaml
- backend/tests/factories.py
Close #98 
1. Was added new endpoint /api/notifications
2. Swagger was changed for /notifications
3. "type" field of Notification model was changed to check NotificationType name
4.  Added clean_data() method for Notification model
Additional: was added creation test notification in seeds.py
Please review.
Thank you in advance for any issues which should be fixed or changed.
Via Postman were created several notifications for requests.
{
"request": "5f8c5227373ab5945b857fe1",
"type": "new_request",
"subject": "Test subject"
}
{
"request": "5f8c5227373ab5945b857fe1",
"type": "canceled_request",
"subject": "Test subject2",
"created_at": "2020-09-10T21:31:16.741Z"
}
> Vb 15 add endpoint for creating a new notification

- backend/app.py
- backend/endpoints/requests.py
- backend/models/request_model.py
Closes #96 
Get Request by ID
1. http://localhost:5000/api/requests/5f8c76e349d06516b0041fd2   - were returned request by id 5f8c76e349d06516b0041fd2
2. http://localhost:5000/api/requests/1  - were returned  is not a valid ObjectId
3. http://localhost:5000/api/requests/5f8c766b49d06516b0041fd1 - were returned Request matching query does not exist.
> Add new endpoint to get a request by ID

- backend/app.py
- backend/endpoints/tags.py
- backend/models/volunteer_model.py
> fixed tags clean_data error and added enums as tags

- backend/app.py
Related https://github.com/code4moldova/voluntar-web/pull/169
> refactor: remove secret endpoint, moved to frontend

- backend/endpoints/user_request.py
Closes #105 
```
{
"has_symptoms": false, 
"number": 3509, 
"status": "new", 
"type": "medicine", 
"urgent": false, 
"first_name": "lala",
"last_name": "lala",
"phone": "68628333",
"landline": "68628333",
"age": 60,
"zone": "botanica",
"address": "stefan cel mare"
}
```
> create new beneficiary and request at the same time

- backend/app.py
> fixed two imports of the same function

- backend/models/volunteer_model.py
> fixed the volunteer model: availability and role

- backend/services/request_service.py
> added filter by volunteer for requests

- backend/services/request_service.py
> filter by cluster and return just one request per cluster

- backend/app.py
- backend/endpoints/__init__.py
- backend/endpoints/export.py
- backend/endpoints/operator.py
- backend/endpoints/tags.py
- backend/endpoints/volunteer.py
- backend/services/table_list.py
- backend/tests/endpoints/test_export.py
- backend/tests/services/test_table_list.py
- backend/tests/unit/test_operator.py
- backend/utils/common.py
Closes #128 
http://localhost:5000/api/export/csv/volunteers
http://localhost:5000/api/export/csv/requests
http://localhost:5000/api/export/csv/beneficiaries
> added export functionality for volunteers, beneficiaries and requests

- backend/endpoints/operator.py
> fix(users): show inactive users when is_active filter is missing

- backend/services/request_service.py
- backend/static/swagger.yaml
> fix(demand): add filter by created_by

- backend/endpoints/requests.py
- backend/static/swagger.yaml
> feat(cluster): add endpoint for cluster requests without auth

- backend/endpoints/import_csv.py
- backend/models/request_model.py
- backend/server.py
- backend/services/table_list.py
- backend/static/swagger.yaml
Closes #126 #134
[import.zip](https://github.com/code4moldova/voluntar-backend/files/5861092/import.zip)
```
curl --request POST \
--url http://localhost:5000/api/import/csv/volunteers \
--header 'authorization: Basic dXJlY2hlQGV4YW1wbGUuY29tOjEyMzQ1Ng==' \
--header 'cache-control: no-cache' \
--header 'content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW' \
--header 'postman-token: e551a658-7e42-43ec-feec-511d019fce15' \
--form file=@volunteers.csv
```
```
curl …
```
> feat(volunteers+requests): import from csv file

- .github/workflows/pythonapp.yml
- Dockerfile
- backend/endpoints/cluster.py
- backend/endpoints/import_csv.py
- backend/endpoints/requests.py
- backend/services/table_list.py
- backend/utils/volunteer_utils.py
> feat: geocoding using tomtom api

- backend/endpoints/beneficiary.py
- backend/endpoints/user_request.py
- backend/models/beneficiary_model.py
- backend/services/request_service.py
- backend/utils/search.py
> feat: search by landline, at least phone or landline
